### ISSUE TITLE
Mantevo : MiniAMR running issue

### ISSUE THREAD

**Issue by Zitagcc** [simgrid/SMPI-proxy-apps#10]
Run it
+ smpirun -np 16 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./miniAMR.x --num_refine 4 --max_blocks 4000 --init_x 1 --init_y 1 --init_z 1 --npx 4 --npy 2 --npz 2 --nx 8 --ny 8 --nz 8 --num_objects 2 --object 2 0 -1.10 -1.10 -1.10 0.030 0.030 0.030 1.5 1.5 1.5 0.0 0.0 0.0 --object 2 0 0.5 0.5 1.76 0.0 0.0 -0.025 0.75 0.75 0.75 0.0 0.0 0.0 --num_tsteps 100 --checksum_freq 4 --stages_per_ts 16
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/privatization' to '1'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '100'
[host-0.hawaii.edu:0:(1) 0.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.19.90/src/smpi/bindings/smpi_mpi.cpp:300: [smpi_mpi/WARNING] Not yet implemented: PMPI_Errhandler_set. Please contact the SimGrid team if support is needed. Run with --log=smpi_mpi.thresh:error to hide
[host-1.hawaii.edu:1:(2) 0.000094] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.19.90/src/simix/smx_global.cpp:268: [xbt/CRITICAL] Process exited without calling MPI_Finalize - Killing simulation
NULL pointer from malloc call in /home/ci/workspace/SMPI-proxy-apps/Benchmarks/Mantevo/MiniAMR/main.c at 529
./miniAMR.x --cfg=smpi/privatization:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI --cfg=smpi/host-speed:100 ./cluster_crossbar.xml smpitmp-appabzM2l
Execution failed with code 134.
--
The full execution report could be found through the following link :  
https://ci.inria.fr/simgrid/job/SMPI-proxy-apps/lastCompletedBuild/testReport/(root)/TestSuite/Mantevo_MiniAMR/

**Comment by adegomme** [comment]
I think that when we discussed about this one, it was found that the "NULL pointer from malloc" was likely coming from the ci system being out of memory (it has only 1 or 2GB, so we have to keep tests small). 
Is it working locally on your computer ?
If yes, you have to find a smaller dataset/input parameters to use

**Comment by Zitagcc** [comment]
Yes we did.
No, it crash with the same error message as well.

**Comment by adegomme** [comment]
I tried it as well, and indeed it allocates way too much memory and made my 16GB system swap.

**Comment by mquinson** [comment]
Is it possible to use other parameters to the test to reduce this memory consumption, maybe?

**Comment by mquinson** [comment]
This was fixed in the meanwhile, thus closing.
