### ISSUE TITLE
Mantevo : HPCCG running issue 

### ISSUE THREAD

**Issue by Zitagcc** [simgrid/SMPI-proxy-apps#11]
Run it
+ smpirun -np 4 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./test_HPCCG 3 5 2
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/privatization' to '1'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '100'
Usage:
Mode 1: 0 nx ny nz
     where nx, ny and nz are the local sub-block dimensions, or
Mode 2: 0 HPC_data_file 
     where HPC_data_file is a globally accessible file containing matrix data.
[host-0.hawaii.edu:0:(1) 0.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.19.90/src/simix/smx_global.cpp:259: [simix_kernel/CRITICAL]    
[host-0.hawaii.edu:0:(1) 0.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.19.90/src/simix/smx_global.cpp:260: [simix_kernel/CRITICAL] The time is still 0, and you still have processes ready to run.
[host-0.hawaii.edu:0:(1) 0.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.19.90/src/simix/smx_global.cpp:261: [simix_kernel/CRITICAL] It seems that you forgot to run the simulation that you setup.
[host-0.hawaii.edu:0:(1) 0.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.19.90/src/simix/smx_global.cpp:262: [xbt/CRITICAL] Bailing out to avoid that stop-before-start madness. Please fix your code.
./test_HPCCG --cfg=smpi/privatization:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI --cfg=smpi/host-speed:100 ./cluster_crossbar.xml smpitmp-appq3MLBk
Execution failed with code 134.
--
[https://ci.inria.fr/simgrid/job/SMPI-proxy-apps/lastCompletedBuild/testReport/(root)/TestSuite/Mantevo_HPCCG/](url)

**Comment by adegomme** [comment]
It appears from the message that this one needs a "0" as a first parameter. Could you try with ./test_HPCCG 0 3 5 2 ?

**Comment by Zitagcc** [comment]
It gives me the following issue message : 
smpirun -np 6 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./test_HPCCG 0 3 5 2
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP-gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '100'
Usage:
Mode 1: 0 nx ny nz
     where nx, ny and nz are the local sub-block dimensions, or
Mode 2: 0 HPC_data_file
     where HPC_data_file is a globally accessible file containing matrix data.
[host-0.hawaii.edu:0:(1) 0.000000] /home/boubehziz/Music/simgrid/src/simix/smx_global.cpp:273: [simix_kernel/WARNING] Process called exit when leaving - Skipping cleanups
[host-0.hawaii.edu:0:(1) 0.000000] /home/boubehziz/Music/simgrid/src/simix/smx_global.cpp:273: [simix_kernel/WARNING] Process called exit when leaving - Skipping cleanups
[host-0.hawaii.edu:0:(1) 0.000000] /home/boubehziz/Music/simgrid/src/simix/smx_global.cpp:273: [simix_kernel/WARNING] Process called exit when leaving - Skipping cleanups
./test_HPCCG --cfg=smpi/privatization:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI --cfg=network/TCP-gamma:4194304 --cfg=smpi/host-speed:100 ./cluster_crossbar.xml smpitmp-appupCwM0
Execution failed with code 1.

**Comment by adegomme** [comment]
This is due to the lack of USING_MPI in the Makefile (line is commented out). This means that we never launch MPI_Init prior to entering the section that reads the arguments... And our smpirun and MPI_Init cheat with them, adding a few temporary ones that MPI_Init then removes.

**Comment by adegomme** [comment]
I found the issue with smpicxx (-std=gnu++11 flag was missing) , I'm pushing the fix in a few moments
