### ISSUE TITLE
CoMD - ECP : Execution has failed

### ISSUE THREAD

**Issue by Zitagcc** [simgrid/SMPI-proxy-apps#3]
smpirun -np 1 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/privatize_global_variables:yes --cfg=smpi/host-speed:100 ./CoMD-mpi
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP-gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/privatize_global_variables' to 'yes'
[0.000000] [xbt_cfg/INFO] Option smpi/privatize_global_variables has been renamed to smpi/privatization. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '100'
Wed Mar  7 11:44:35 2018: Starting Initialization

Mini-Application Name    : CoMD-mpi
Mini-Application Version : 1.1
Platform:
  hostname: tboubehz-hp
  kernel name: 'Linux'
  kernel release: '4.13.0-36-generic'
  processor: 'x86_64'
Build:
  CC: '/usr/local/bin/smpicc'
  compiler version: 'SimGrid version 3.16-DEVEL'
  CFLAGS: ' -DDOUBLE -DDO_MPI -g -O5   '
  LDFLAGS: ' -lm '
  using MPI: true
  Threading: none
  Double Precision: true
Run Date/Time: 2018-03-07, 11:44:35

Command Line Parameters:
  doeam: 0
  potDir: pots
  potName: Cu_u6.eam
  potType: funcfl
  nx: 20
  ny: 20
  nz: 20
  xproc: 1
  yproc: 1
  zproc: 1
  Lattice constant: -1 Angstroms
  nSteps: 100
  printRate: 10
  Time step: 1 fs
  Initial Temperature: 600 K
  Initial Delta: 0 Angstroms

smpimain: /home/boubehziz/Downloads/SMPI-proxy-apps/Benchmarks/CoMD/src-mpi/haloExchange.c:412: unloadAtomsBuffer: Assertion `bufSize % sizeof(AtomMsg) == 0' failed.
./CoMD-mpi --cfg=smpi/privatization:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI --cfg=network/TCP-gamma:4194304 --cfg=smpi/privatize_global_variables:yes --cfg=smpi/host-speed:100 ./cluster_crossbar.xml smpitmp-app5t7xPL
Execution failed with code 134.

**Comment by adegomme** [comment]
Hi,

this should be fixed by https://github.com/simgrid/simgrid/commit/9dfe23fdf9abd1568ce357de2a0573726948b2c2
The MPI_Status used in a MPI_Sendrecv operation was not set properly if the operation was identified as local and replaced by a single copy.
