### ISSUE TITLE
Trinity-Nersc : Stream app doesn't work here!! 

### ISSUE THREAD

**Issue by Zitagcc** [simgrid/SMPI-proxy-apps#7]
On my own machine it works well.
--- 
Clean up the place
+ rm -rf Benchmarks/steam
+ mkdir -p Benchmarks/stream
+ cd Benchmarks
+ echo Download the source
Download the source
+ test -e stream-source.tgz
+ echo Unpack the code
Unpack the code
+ tar -xvf stream-source.tgz -C stream
Makefile
README.NERSC
mysecond.c
runit
stream.c
stream.f
stream_omp.c
+ echo Install the modified sources
Install the modified sources
+ pwd
/home/ci/workspace/SMPI-proxy-apps/Benchmarks
+ cp -f ../src/Trinity-Nersc/stream/Makefile stream/
+ cp -f ../src/common/cluster_crossbar.xml ../src/common/cluster_hostfile.txt stream/
+ cd stream
+ echo Compile it
Compile it
+ make
make: Nothing to be done for 'all'.
+ echo Run it
Run it
+ smpirun -np 4 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./stream_c.exe
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/privatization' to '1'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '100'
[host-0.hawaii.edu:0:(1) 0.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-stable/build/SimGrid-3.18.90/src/smpi/internals/smpi_global.cpp:537: [xbt/CRITICAL] dlopen failed: libsimgrid.so.3.19: cannot open shared object file: No such file or directory (errno: 0 -- Success)
./stream_c.exe --cfg=smpi/privatization:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI --cfg=smpi/host-speed:100 ./cluster_crossbar.xml smpitmp-appmKN9N9
Execution failed with code 134.

**Comment by adegomme** [comment]
[xbt/CRITICAL] dlopen failed: libsimgrid.so.3.19: cannot open shared object file: No such file or directory

someone changed the version number, so it's libsimgrid.so.3.18.90 that should be used ... so it seems nothing was recompiled.
I see a typo in the first line, you are removing steam folder, not stream one. 
this would explain the "make: Nothing to be done for 'all'." which says that everything was already generated

**Comment by Zitagcc** [comment]
Thank you for the hint, It worked.
